### ISSUE TITLE
Keep screenshots up-to-date by cross linking

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview-academy#9]
@terrymyc suggests using screenshots from the ASReview docs folder (if possible) to avoid they will become outdated. 

Like using https://github.com/asreview/asreview/blob/master/docs/images/setup_datasets_simulate_benchmark.png instead of https://github.com/asreview/asreview-academy/blob/main/introducing-ASReview-LAB/images/Interface5.png

**Comment by VeenDuco** [comment]
I'll pick this up

**Comment by VeenDuco** [comment]
See #26, This is not always possible as we display other things then are relevant to the docs. So some figures will have to live in this repository and be updated when they are outdated.  For now I've replaces what's possible and needed, e.g. making sure we have validation mode figures instead of exploration.
